'''a=int(input())
b=int(input())
print(a+b)
l=[1,2,3,4]
l.append(5)
print(l)
t=(1,2,2,2,4)
a=t.count(2)
b=t.index(2)
print(a,b)
d={"himachal":"ishita","jammu":"shivi","kangra":"prachi"}
print(d["himachal"],d["jammu"])
a=len("ishita")
print(a)
a=23
b=2.34
print(a+b)'''
l=[1,2,3,4,5]
l.remove(1)
print(l)
